name: ben
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - ipython=8.1.1
  - jupyterlab=3.3.0
  - pip=21.2.2
  - pyaudio=0.2.11
  - python=3.8.12
  - pytorch=1.10.2
  - torchaudio=0.10.2
  - pip:
    - matplotlib==3.5.1
    - scikit-learn==1.0.2
    - scipy==1.8.0
    - soundfile==0.10.3.post1
